### PR TITLE
Edits to manuscript and other files

### PR DESCRIPTION
**Pull request by joglekara**
Edits as requested by @TomGoffrey

### CODE REVIEW

**Comment by TomGoffrey** [comment]
Thanks @joglekara from a quick check these look great.

**Comment by joglekara** [comment]
@TomGoffrey, any more thoughts on this one or should I go ahead and merge?

**Comment by TomGoffrey** [comment]
Also looks good to me.

**Comment by joglekara** [comment]
Thanks all!

**Pull request merged**
